version: '2.0'
services:
  db:
    build: './db'
  backend:
    build: './backend'
    ports:
      - '3000:3000'
    environment:
      - DB_URL=db
    depends_on:
      - db
  graphql:
    build: './graphql'
    ports:
      - '4000:4000'
    environment:
      - BACKEND_URL=backend
    depends_on:
      - backend